Parameters:
  
  BaseName:
    Type: String

  NumberOfAZs:
    Type: Number
    AllowedValues:
    - 1
    - 2
    - 3
    Default: 2
    Description:  How many Availability Zones do you wish to utilize?

  PrivateSubnets:
    Type: String
    AllowedValues:
    - True
    - False
    Default: True
    Description: Do you want to create private subnets in addition to public subnets?

  VpcCIDR:
    Description: Enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 17.31.0.0/16

  PublicSubnet1CIDR:
    Description: Enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 17.31.10.0/24

  PublicSubnet2CIDR:
    Description: Enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: 17.31.11.0/24

  PublicSubnet3CIDR:
    Description: Enter the IP range (CIDR notation) for the public subnet in the third Availability Zone
    Type: String
    Default: 17.31.12.0/24

  PrivateSubnet1CIDR:
    Description: Enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 17.31.20.0/24

  PrivateSubnet2CIDR:
    Description: Enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 17.31.21.0/24



  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: 9
    MaxLength: 18
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x
    Default: 0.0.0.0/0


  
  TcpPort:
    Description: Enter TCP Port number.
    Type: Number
    Default: 3306


Conditions:
  BuildPublicSubnet2: !Not [ !Equals [ !Ref NumberOfAZs, 1 ]] 
  BuildPublicSubnet3: !Equals [ !Ref NumberOfAZs, 3 ]
  BuildPrivateSubnets: !Equals [ !Ref PrivateSubnets, True ]
  BuildPrivateSubnet1: !Equals [ !Ref PrivateSubnets, True ]
  BuildPrivateSubnet2: !And [ !Not [ !Equals [ !Ref NumberOfAZs, 1 ]], !Equals [ !Ref PrivateSubnets, True ]]


Resources:



  # ApplicationServerSecurityGroup:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties: 
  #     VpcId: !Ref VPC
  #     GroupDescription: Enable access through Web Sever only
  #     SecurityGroupIngress:
          
  #       - IpProtocol: tcp
  #         FromPort: 22
  #         ToPort: 22
  #         CidrIp: !Ref PublicSubnet1CIDR
              
  #       - IpProtocol: tcp
  #         FromPort: 3306
  #         ToPort: 3306
  #         CidrIp: !Ref PublicSubnet1CIDR

  #       - IpProtocol: tcp
  #         FromPort: 22
  #         ToPort: 22
  #         CidrIp: !Ref PublicSubnet2CIDR

  #       - IpProtocol: tcp
  #         FromPort: 3306
  #         ToPort: 3306
  #         CidrIp: !Ref PublicSubnet2CIDR

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Enable SSH and tcp access via port 22 and 80, respectively
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: !Ref SSHLocation
      
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  # PublicLoadBalancerSG:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties: 
  #     VpcId: !Ref VPC
  #     GroupDescription: Security group to allow access to instances through Load Balancer
  #     GroupName: alamcf-PublicLoadBalancerSG
  #     SecurityGroupIngress:
  #     - IpProtocol: tcp
  #       FromPort: 80
  #       ToPort: 80
  #       CidrIp: 39.32.0.0/16

  #     - IpProtocol: tcp
  #       FromPort: 443
  #       ToPort: 443
  #       CidrIp: 39.32.0.0/0

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref BaseName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref BaseName

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${BaseName} Public Subnet (AZ1)

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Condition: BuildPublicSubnet2
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${BaseName} Public Subnet (AZ2)

  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Condition: BuildPublicSubnet3
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [2, !GetAZs ""]
      CidrBlock: !Ref PublicSubnet3CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${BaseName} Public Subnet (AZ3)  

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Condition: BuildPrivateSubnet1
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${BaseName} Private Subnet (AZ1)

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Condition: BuildPrivateSubnet2
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: !Ref PrivateSubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${BaseName} Private Subnet (AZ2)

  NatGateway1EIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc

  NatGateway2EIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc

  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: !Ref BaseName

  NatGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway2EIP.AllocationId
      SubnetId: !Ref PublicSubnet2
      Tags:
        - Key: Name
          Value: !Ref BaseName

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${BaseName} Public Routes

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: BuildPublicSubnet2
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2

  PublicSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: BuildPublicSubnet3
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet3

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${BaseName} Private Routes (AZ1)

  DefaultPrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway1

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: BuildPrivateSubnet1
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: !Ref PrivateSubnet1

  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Condition: BuildPrivateSubnet2
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${BaseName} Private Routes (AZ2)

  DefaultPrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway2

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      SubnetId: !Ref PrivateSubnet2

  # RdsSecurityGroup:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupDescription: App Server to RDS access
  #     VpcId: !Ref VPC
  #     Tags: 
  #       - Key: Name
  #         Value: !Ref BaseName
  #     SecurityGroupIngress:
  #       - IpProtocol: tcp
  #         FromPort: !Ref TcpPort
  #         ToPort: !Ref TcpPort
  #         CidrIp: !Ref PrivateSubnet1CIDR

  #       - IpProtocol: tcp
  #         FromPort: 3306
  #         ToPort: 3306
  #         CidrIp: !Ref PrivateSubnet1CIDR

  # AccessSecurityGroupIngress:
  #   Type: AWS::EC2::SecurityGroupIngress
  #   DependsOn: RdsSecurityGroup
  #   Properties:
  #     GroupId: !Ref RdsSecurityGroup
  #     IpProtocol: tcp
  #     FromPort: !Ref TcpPort
  #     ToPort: !Ref TcpPort
  #     SourceSecurityGroupId: !Ref RdsSecurityGroup
  #     Tags:
  #       - Key: Name
  #         Value: !Ref BaseName

  # DbSubnetGroup:
  #   Type: AWS::RDS::DBSubnetGroup
  #   Properties:
  #     DBSubnetGroupDescription: 'Database Subnet Group'
  #     SubnetIds:
  #     - !Ref PrivateSubnet1
  #     - !Ref PrivateSubnet2
  #     Tags:
  #       - Key: Name
  #         Value: !Ref BaseName


Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC
    Export:
      Name: !Sub "alamstack-VPC"

  PublicSubnets:
    Description: A list of the public subnets
    Value: !Join [",", [!Ref PublicSubnet1, !Ref PublicSubnet2]]


  PrivateSubnets:
    Description: A list of the private subnets
    Value: !Join [",", [!Ref PrivateSubnet1, !Ref PrivateSubnet2]]

  PublicSubnet1:
    Description: A reference to the public subnet in the 1st Availability Zone
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub "alamstack-PublicSubnet1"

  PublicSubnet2:
    Description: A reference to the public subnet in the 2nd Availability Zone
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub "alamstack-PublicSubnet2"

  PrivateSubnet1:
    Description: A reference to the private subnet in the 1st Availability Zone
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub "alamstack-PrivateSubnet1"

  # PrivateSubnet2:
  #   Description: A reference to the private subnet in the 2nd Availability Zone
  #   Value: !Ref PrivateSubnet2





  # ApplicationServerSecurityGroup:
  #   Description: Private Security Group
  #   Value: !Ref ApplicationServerSecurityGroup
  #   Export:
  #     Name: !Sub "alamstack-ApplicationServerSecurityGroup"

  InstanceSecurityGroup:
    Description: Public Sever Security Group
    Value: !Ref InstanceSecurityGroup
    Export:
      Name: !Sub "alamstack-InstanceSecurityGroup"


  # InternetGateway:
  #   Description: Internet Gateway
  #   Value: !Ref InternetGateway

  # InternetGatewayAttachment:
  #   Description: Internet Gateway Attachment 
  #   Value: !Ref InternetGatewayAttachment


  # NatGateway1EIP:
  #   Description: NatGateway 1 EIP
  #   Value: !Ref NatGateway1EIP

  # NatGateway2EIP:
  #   Description: NatGateway 2 EIP
  #   Value: !Ref NatGateway2EIP

  # NatGateway1:
  #   Description: NatGateway 1
  #   Value: !Ref NatGateway1

  # NatGateway2:
  #   Description: NatGateway 2
  #   Value: !Ref NatGateway2

  # PublicRouteTable:
  #   Description: Public Route Table
  #   Value: !Ref PublicRouteTable

  # DefaultPublicRoute:
  #   Description: Default Public Route
  #   Value: !Ref DefaultPublicRoute

  # PublicSubnet1RouteTableAssociation:
  #   Description: PublicSubnet 1 Route Table Association
  #   Value: !Ref PublicSubnet1RouteTableAssociation

  # PublicSubnet2RouteTableAssociation:
  #   Description: Public Subnet 2 Route Table Association
  #   Value: !Ref PublicSubnet2RouteTableAssociation

  # PublicSubnet3RouteTableAssociation:
  #   Description: Public Subnet 3 Route Table Association
  #   Value: !Ref PublicSubnet3RouteTableAssociation

  # PrivateRouteTable1:
  #   Description: Private Route Table 1
  #   Value: !Ref PrivateRouteTable1

  # DefaultPrivateRoute1:
  #   Description: Default Private Route 1
  #   Value: !Ref DefaultPrivateRoute1

  # PrivateSubnet1RouteTableAssociation:
  #   Description: Private Subnet 1 Route Table Association 
  #   Value: !Ref PrivateSubnet1RouteTableAssociation

  # PrivateRouteTable2:
  #   Description:  Private Route Table 2
  #   Value: !Ref PrivateRouteTable2

  # DefaultPrivateRoute2:
  #   Description: Default Private Route 2 
  #   Value: !Ref DefaultPrivateRoute2

  # PrivateSubnet2RouteTableAssociation:
  #   Description: Private Subnet 2 Route Table Association
  #   Value: !Ref PrivateSubnet2RouteTableAssociation

  # RdsSecurityGroup:
  #   Description: Rds Security Group 
  #   Value: !Ref RdsSecurityGroup
  #   Export:
  #     Name: !Sub "alamstack-RdsSecurityGroup"

  # AccessSecurityGroupIngress:
  #   Description: Access Security Group Ingress 
  #   Value: !Ref AccessSecurityGroupIngress

  # DbSubnetGroup:
  #   Description: Database Subnet Group 
  #   Value: !Ref DbSubnetGroup
  #   Export:
  #     Name: !Sub "alamstack-DbSubnetGroup"

  # PublicLoadBalancerSG:
  #   Value: !Ref PublicLoadBalancerSG
  #   Export:
  #     Name: !Sub "alamstack-PublicLoadBalancerSG"